- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Use your username autostart.desktop files
    replace:
      path: "{{ item }}"
      regexp: 'yourusername'
      replace: "{{ ansible_user_id }}"
    with_fileglob: autostart/*

  - name: Copy all desktop files to local autostart
    copy:
      src: "{{item}}"
      dest: /home/{{ ansible_user_id }}/.config/autostart/
      force: yes
    with_fileglob: autostart/*
