- name: Autostart
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Use your username autostart.desktop files
    replace:
      path: "{{ item }}"
      regexp: 'yourusername'
      replace: "{{ ansible_user_id }}"
    with_fileglob: autostart/*

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/.config/autostart directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.config/autostart"
      state: directory

  - name: Copy all desktop files to local autostart
    copy:
      src: "{{item}}"
      dest: "{{ user_home.stdout_lines[0] }}/.config/autostart/"
      force: yes
    with_fileglob: autostart/*
