- name:
  hosts: 127.0.0.1
  vars:
    autops_package: "Automation-1.2.11a0-py2-none-any.whl"
  connection: local
  tasks:
  - name: Install packages
    apt: name={{item}} state=present
    with_items:
    - python
    - python-pip
    - python-dev
    - git
    - git-flow
    - libpcap-dev
    - libdbus-glib-1-dev
    become: true
  - name: Install PyCharm using snap
    command: snap install pycharm-community --classic  # waiting for snap module to get rid of command
    become: true
  - name: Set network capabilities for python2.7  # required for running autops without sudo
    capabilities:
      path: /usr/bin/python2.7
      capability: cap_net_admin,cap_net_raw+eip
      state: present
    become: true
  - name: Install autops
    pip:
      name: file://{{playbook_dir}}/{{autops_package}}
      state: present
