- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  #Based on: https://bendews.com/posts/implement-dns-over-https/
  #https://galaxy.ansible.com/bendews/cloudflared
  - name: Install and Configure cloudflared - dns over https
    include_role:
      name: bendews.cloudflared
    vars:
      cloudflared_allow_firewall: false
      cloudflared_enable_service: true
      cloudflared_port: 53
      ansible_become: true

  #1. I have to edit role to set become: true, where we need sudo support
  #2. I gave to execute additionally 
  # $ sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/cloudflared

  #to set dns check:
  #https://askubuntu.com/questions/1033292/ubuntu-18-04-using-netplan-with-dhcp-and-static-dns-settings-seems-totally-broke
  #do not work on usb system to check after installation standalone elementary

