- name: qnapi
  hosts: 127.0.0.1
  connection: local
  tags: elementary-os
  tasks:

  - name: Add qnapi Repository
    apt_repository:
      repo: ppa:philip.scott/elementary-tweaks
    become: true

  - name: Install qnapi
    apt:
      name: elementary-tweaks
      update_cache: yes
      state: latest
    become: true
