- name:
  hosts: 127.0.0.1
  tags: jetbrains
  connection: local
  tasks:

  - name: Install python3
    apt:
      name: python3
      update_cache: yes
      state: latest
    become: true

  - name: Remove/change system shortcuts with collisions for Jetbrains products
    shell: "python3 shortcuts/clearSystemShortcuts.py  -e"
