- name:
  hosts: 127.0.0.1
  connection: local
  tags: keepassxc
  tasks:

  - name: Add KeepassXC Repository
    apt_repository:
      repo: ppa:phoerious/keepassxc
    become: true

  - name: Install KeepassXC
    apt:
      name: keepassxc
      update_cache: yes
      state: latest
    become: true

  - name: grep and register
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/.config/keepassxc directory is present
    file:
      path: "{{ user_home }}/.config/keepassxc"
      state: directory

  - name: copy local keepassxc.ini to remote if exists
    stat:
      path: keepassxc/keepassxc.ini
    register: keepassxcini

  - name: copy keepassxc configuration
    when: keepassxcini.stat.exists
    copy:
      src: keepassxc/keepassxc.ini
      dest: "{{ user_home }}/.config/keepassxc/keepassxc.ini"
      force: yes
