- name:
  hosts: 127.0.0.1
  connection: local
  tags: keepassxc
  tasks:

  - name: Add KeepassXC Repository
    apt_repository:
      repo: ppa:phoerious/keepassxc
    become: true

  - name: Install KeepassXC
    apt:
      name: keepassxc
      update_cache: yes
      state: latest
    become: true

