- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install multimedia codecs
    apt: name={{item}} state=present
    with_items:
    - ubuntu-restricted-extras
    - libavcodec-extra
    - libdvd-pkg
    become: true
