- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add UNetbootin Repository
    apt_repository:
      repo: ppa:gezakovacs/ppa
      tags:
        - unetbootin
      become: true

  - name: Install Ubuntu packages
    apt: name={{item}} state=present
    with_items:
    - tree
    - httpie
    # https://httpie.org/
    - tldr
    - python
    - python-pip
    - python3
    - python3-pip
    - file-roller
    - audacity
    - bleachbit
    - dconf-editor
    - baobab
    - gnome-font-viewer
    - gnome-disk-utility
    - gnome-system-monitor
    - gnome-power-manager
    - gnome-tweak-tool
    - gdebi-core
    - gparted
    - menulibre
    - pinta
    - pulseaudio
    - remmina
    - transmission
    - vlc
    - unetbootin
    become: true