- name:
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install packages
    apt: name={{item}} state=present
    with_items:
    - tldr
    - python
    - python-pip
    - python3
    - python3-pip
    - pinta
    become: true

