- name: Vim
  hosts: 127.0.0.1
  connection: local
  tags: vim
  tasks:

  - name: Install vim
    apt: 
      name: vim 
      state: present
    become: true

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/.vim/undodir directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.vim/undodir"
      state: directory

  - name: copy .vimrc to local user configuration
    copy:
      src: vim/vimrc
      dest: "{{ user_home.stdout_lines[0] }}/.vimrc"
      force: yes

