- name: virtualbox
  hosts: 127.0.0.1
  connection: local
  tags: virtualbox
  tasks:

  - name: Add the Virtualbox APT new key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
    become: true

  - name: Add the Virtualbox APT old key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present
    become: true

  - name: Add Virtualbox Repository
    apt_repository:
      repo: "deb https://download.virtualbox.org/virtualbox/debian bionic contrib"
      state: present
      filename: virtualbox.list
    become: true

  - name: Install Virtualbox
    apt:
      name: "{{ package }}"
      update_cache: yes
      state: latest
    vars:
      package:
      - virtualbox-5.2
      - dkms
    become: true
