- name: to check how to properly install it
  hosts: 127.0.0.1
  connection: local
  tags: elementary-os
  tasks:

  - name: ensure the ~/.config/autostart directory is present
    file:
      path: /home/{{ ansible_user_id }}/.config/autostart
      state: directory

  - name: copy indicator-application.desktop to user home autostart
    copy:
      src: /etc/xdg/autostart/indicator-application.desktop
      dest: /home/{{ ansible_user_id }}/.config/autostart/
      force: yes

  - replace:
      path: /home/{{ ansible_user_id }}/.config/autostart/indicator-application.desktop
      regexp: 'OnlyShowIn.*'
      replace: 'OnlyShowIn=Unity;GNOME;Pantheon;'

  - name: Install a last .deb package from the internet for install wingpanel-indicator-ayatana
    apt:
      deb: "https://launchpad.net/%7Eelementary-os/+archive/ubuntu/stable/+files/wingpanel-indicator-ayatana_2.0.3+r27+pkg17%7Eubuntu0.4.1.1_amd64.deb"
    become: true

  - replace:
      path: /usr/share/themes/elementary/gtk-3.0/apps.css
      regexp: '.composited-indicator.*\n\s*padding: 0 \dpx;'
      replace: '.composited-indicator {\n    padding: 0 2px;'
    become: true

 #Based on:
 #https://elementaryos.stackexchange.com/questions/16502/missing-icons-in-the-wingpanel 
 #https://elementaryos.stackexchange.com/questions/7550/dropbox-icon-missing-in-loki
 #https://github.com/mdh34/elementary-indicators
