- name: to check how to properly install it
  hosts: 127.0.0.1
  connection: local
  tags: elementary-os
  tasks:

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/.config/autostart directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.config/autostart"
      state: directory

  - name: ensure the ~/.config/autostart directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.config/autostart"
      state: directory

  - name: copy indicator-application.desktop if exists
    stat:
      path: /etc/xdg/autostart/indicator-application.desktop
    register: indicatorappdesktop

  - name: copy indicator-application.desktop to user home autostart
    copy:
      src: /etc/xdg/autostart/indicator-application.desktop
      dest: "{{ user_home.stdout_lines[0] }}/.config/autostart/"
      force: yes
    when: indicatorappdesktop.stat.exists

  - replace:
      path: "{{ user_home.stdout_lines[0] }}/.config/autostart/indicator-application.desktop"
      regexp: 'OnlyShowIn.*'
      replace: 'OnlyShowIn=Unity;GNOME;Pantheon;'
    when: indicatorappdesktop.stat.exists

  - name: Install a last .deb package from the internet for install wingpanel-indicator-ayatana
    apt:
      deb: "https://launchpad.net/%7Eelementary-os/+archive/ubuntu/stable/+files/wingpanel-indicator-ayatana_2.0.3+r27+pkg17%7Eubuntu0.4.1.1_amd64.deb"
    become: true
    tags: no-tests

  - name: Correct padding in app.css if it exists
    stat:
      path: /usr/share/themes/elementary/gtk-3.0/apps.css
    register: appscss

  - replace:
      path: /usr/share/themes/elementary/gtk-3.0/apps.css
      regexp: '.composited-indicator.*\n\s*padding: 0 \dpx;'
      replace: '.composited-indicator {\n    padding: 0 2px;'
    become: true
    when: appcss.stat.exists


 #Based on:
 #https://elementaryos.stackexchange.com/questions/16502/missing-icons-in-the-wingpanel 
 #https://elementaryos.stackexchange.com/questions/7550/dropbox-icon-missing-in-loki
 #https://github.com/mdh34/elementary-indicators
