- name:
  hosts: 127.0.0.1
  connection: local
  tags: yakuake
  tasks:
  
  - name: Instal yakuake
    apt:
      name: yakuake
      update_cache: yes
      state: latest
    become: true

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home
  
  - name: ensure the ~/.local/share/konsole directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.local/share/konsole"
      state: directory

  - name: copy konsole profiles
    synchronize:
      src: zsh_files/konsole_profiles/konsole
      dest: "{{ user_home.stdout_lines[0] }}/.local/share/"

  - name: ensure the /usr/share/yakuake/skins/ directory is present
    file:
      path: /usr/share/yakuake/skins/
      state: directory
    become: true

  - name: copy yakuake skins
    synchronize:
      src: zsh_files/yakuake_skins/
      dest: /usr/share/yakuake/
    become: true

  - name: copy yakuakerc
    copy:
      src: zsh_files/yakuakerc
      dest: "{{ user_home.stdout_lines[0] }}/.config/"

  - name: copy yakuake skins
    synchronize:
      src: zsh_files/konsoleprofile
      dest: "{{ user_home.stdout_lines[0] }}/.local/bin/"

