- name:
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Add Yubico Repository
  - apt_repository:
    repo: ppa:yubico/stable
    tags:
    - keepassxc
    become: true
  - name: Install Yubico Tools
    apt: name={{item}} state=latest
    with_items:
      - yubikey-manager-qt
      - yubioath-desktop
      - yubikey-personalization-gui
      - yubikey-piv-manager
    update_cache: yes
    become: true

