---
- name: Test elementary-as-a-code
  hosts: 127.0.0.1
  connection: local

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "@Development tools"
        - tar
        - unzip
        - sudo
        - which
      when: ansible_os_family == 'RedHat'

    - name: Ensure build dependencies are installed (Debian)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - unzip
        - tar
        - sudo
      when: ansible_os_family == 'Debian'

- import_playbook: ../ubuntu-playbook.yml
