- name: Crypo packages
  hosts: 127.0.0.1
  connection: local
  tags: crypto
  tasks:

  - name: Install cryptographic packages
    apt: name="{{packages}}" state=present
    vars:
      packages:
      - opensc
      - openssl
      - libengine-pkcs11-openssl1.1
      # installs certtool for easy ssl key management
      - gnutls-bin
    become: true
