- name: DNS over https
  hosts: 127.0.0.1
  connection: local
  tags: cloudflared-dns
  tasks:

  #Based on: https://bendews.com/posts/implement-dns-over-https/
  #https://galaxy.ansible.com/bendews/cloudflared
  - name: Install and Configure cloudflared - dns over https
    include_role:
      name: bendews.cloudflared
    vars:
      cloudflared_allow_firewall: false
      cloudflared_enable_service: true
      cloudflared_port: 53
      ansible_become: true

# Wait for fix:
# https://askubuntu.com/questions/973017/wrong-nameserver-set-by-resolvconf-and-networkmanager
# https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320

  - name: Configure systemd-resolvconf to use default local dns server
    replace:
      path: /etc/systemd/resolved.conf
      regexp: '\#DNS\='
      replace: 'DNS=127.0.0.1'
    become: true
    register: resolvedConf

  - name: Link proper resolv.conf
    file:
      src: /run/systemd/resolve/resolv.conf
      dest: /etc/resolv.conf
      force: yes
      state: link
    become: true
    tags: no-tests
