- name: Dropbox for elementary os installation
  hosts: 127.0.0.1
  connection: local
  tags: elementary-os
  tasks:

  - name: Install git and wget
    apt:
      name: "{{ package }}"
      state: present
    become: true
    vars:
      package:
        - git
        - wget

  - name: Clone git repository with script to install dropbox
    git:
      repo: https://github.com/zant95/elementary-dropbox
      dest: /tmp/elementary-dropbox

  - name: grep and register
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: install dropbox if its binary does not exists
    stat:
      path: "{{ user_home.stdout_lines[0] }}/.dropbox-bin"
    register: dropboxbin
 
  - name: Install dropbox by script
    shell: /tmp/elementary-dropbox/install.sh -y
    when: not dropboxbin.stat.exists

