- name: grub-customizer
  hosts: 127.0.0.1
  connection: local
  tags: grub customizer
  tasks:

  - name: Add grub-customizer Repository
    apt_repository:
      repo: ppa:danielrichter2007/grub-customizer
    become: true

  - name: Install grub-customizer
    apt:
      name: grub-customizer
      update_cache: yes
      cache_valid_time: 7200
      state: latest
    become: true

