- name: Idea keymap
  hosts: 127.0.0.1
  tags: jetbrains
  connection: local
  tasks:

  - name: Install python3
    apt:
      name: python3
      update_cache: yes
      cache_valid_time: 7200
      state: latest
    become: true

  - name: install dropbox if its binary does not exists
    stat:
      path: "clearSystemShortcuts.executed"
    register: clearSystemShortcutsExecuted

  - name: Remove/change system shortcuts with collisions for Jetbrains products
    shell: "python3 shortcuts/clearSystemShortcuts.py  -e && touch clearSystemShortcuts.executed"
    when: not clearSystemShortcutsExecuted.stat.exists
