- name: Multimedia codecs
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install multimedia codecs
    apt: name="{{package}}" state=present
    vars:
      package:
      - ubuntu-restricted-extras
      - libavcodec-extra
      - ffmpeg
    become: true
