- name: Plank
  hosts: 127.0.0.1
  tags: elementary-os
  connection: local
  tasks:

  - name: Install packages for Plank
    apt: name="{{packages}}" state=present
    vars:
      packages:
        - python-psutil
        - python3-psutil
        - zlib1g-dev
        - dconf-cli
        - psmisc
    become: true

  - name: Add Plank Repository
    apt_repository:
      repo: ppa:ricotz/docky
    become: true

  - name: Install plank
    apt:
      name: plank
      update_cache: yes
      cache_valid_time: 7200
      state: latest
    become: true
    register: plankInst

  - name: Configure plank
    dconf:
      key: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
    loop:
      - { name: "/net/launchpad/plank/docks/dock1/icon-size", value: "50" }
      - { name: "/net/launchpad/plank/docks/dock1/show-dock-item", value: "false" }
      - { name: "/net/launchpad/plank/docks/dock1/position", value: "'bottom'" }
      - { name: "/net/launchpad/plank/docks/dock1/unhide-delay", value: "0" }
      - { name: "/net/launchpad/plank/docks/dock1/items-alignment", value: "'center'" }
      - { name: "/net/launchpad/plank/docks/dock1/theme", value: "'Transparent'" }
      - { name: "/net/launchpad/plank/docks/dock1/hide-mode", value: "'Intellihide'" }
      - { name: "/net/launchpad/plank/docks/dock1/pinned-only", value: "false" }
      - { name: "/net/launchpad/plank/docks/dock1/auto-pinning", value: "true" }
      - { name: "/net/launchpad/plank/docks/dock1/alignment", value: "'center'" }
      - { name: "/net/launchpad/plank/docks/dock1/zoom-percent", value: "150" }
      - { name: "/net/launchpad/plank/docks/dock1/hide-delay", value: "0" }
      - { name: "/net/launchpad/plank/docks/dock1/zoom-enabled", value: "true" }
      - { name: "/net/launchpad/plank/docks/dock1/monitor", value: "''" }
      - { name: "/net/launchpad/plank/docks/dock1/lock-items", value: "false" }
      - { name: "/net/launchpad/plank/docks/dock1/tooltips-enabled", value: "true" }
      - { name: "/net/launchpad/plank/docks/dock1/pressure-reveal", value: "false" }
      - { name: "/net/launchpad/plank/docks/dock1/offset", value: "0" }
      - { name: "/net/launchpad/plank/docks/dock1/current-workspace-only", value: "false" }

  - name: Restart plank
    shell: "killall -9 plank"
    when: plankInst.changed
    tags: no-tests
