- name: qnapi
  hosts: 127.0.0.1
  connection: local
  tags: qnapi
  tasks:

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/bin directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/bin"
      state: directory
      mode: 0777

  - name: Download QNapi to home bin directory
    get_url:
      url: https://github.com/QNapi/qnapi/releases/download/0.2.3/QNapi-0.2.3-x86_64.AppImage
      dest: "{{ user_home.stdout_lines[0] }}/bin/"

  - name: Download QNapi icon to home bin directory
    get_url:
      url: https://qnapi.github.io/images/qnapi-128.png
      dest: "{{ user_home.stdout_lines[0] }}/bin/"

  - name: Use your user home in qnapi.desktop shortcut
    replace:
      path: conf-files/qnapi.desktop
      regexp: '\/home\/yourusername'
      replace: "{{ user_home.stdout_lines[0] }}"

  - name: Copy qnapi.desktop to be visible in start menu
    copy:
      src: conf-files/qnapi.desktop
      dest: "{{ user_home.stdout_lines[0] }}/.local/share/applications/qnapi.desktop"
      force: yes

  - name: copy local qnapi.ini to remote if not exists
    stat:
      path: conf-files/qnapi.ini
    register: qnapi_ini

  - name: copy qnapi configuration
    when: not qnapi_ini.stat.exists
    copy:
      src: conf-files/qnapi.ini
      dest: "{{ user_home.stdout_lines[0] }}/.config/qnapi.ini"
      force: yes