- name: Terminal tools
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install packages
    apt: name="{{package}}" state=present
    vars:
      package:
      - screen
      - git-core
      - powerline
      - zsh
    become: true
