- name: Utilities
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add UNetbootin Repository
    apt_repository:
      repo: ppa:gezakovacs/ppa
    become: true

  - name: Install Ubuntu packages
    apt: name="{{packages}}" state=present
    vars:
      packages:
      - cargo
      - tree
      - httpie
      # https://httpie.org/
      - tldr
      - python
      - python-pip
      - python3
      - python3-pip
      - file-roller
      - audacity
      - bleachbit
      - dconf-editor
      - baobab
      - gnome-font-viewer
      - gnome-disk-utility
      - gnome-system-monitor
      - gnome-power-manager
      - gnome-tweak-tool
      - gdebi-core
      - gparted
      - htop
      # For network issues debugging
      - iptraf
      - iftop
      - menulibre
      - pinta
      - pulseaudio
      - remmina
      - transmission
      - vlc
      - unetbootin
      - unace
      - rar
      - unrar
      - p7zip-rar
      - p7zip
      - sharutils
      - uudeview
      - mpack
      - arj
      - cabextract
      - lzip
      - lunzip
      - shutter
    become: true

  - name: install exa if its binary does not exists
    stat:
      path: "exa.executed"
    register: exaExecuted
    tags: no-tests

  - name: Install exa with cargo package manager
    shell: "cargo install exa && touch exa.executed"
    when: not exaExecuted.stat.exists
    tags: no-tests

  - name: Install tokei (tool to count nr of lines) with cargo package manager
    shell: "cargo install tokei"
    tags: no-tests

  - name: Install sd (better sed) with cargo package manager
    shell: "cargo install sd"
    tags: no-tests

  - name: Install fd (better find)
    apt:
      deb: "https://github.com/sharkdp/fd/releases/download/v7.3.0/fd_7.3.0_amd64.deb"
    become: true
    tags: no-tests

  - name: Install ripgrep (better grep)
    apt:
      deb: "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb"
    become: true
    tags: no-tests

  - name: Install bat (better cat)
    apt:
      deb: "https://github.com/sharkdp/bat/releases/download/v0.11.0/bat_0.11.0_amd64.deb"
    become: true
    tags: no-tests

  - name: Install hyperfine (benchmark for terminal apps)
    apt:
      deb: "https://github.com/sharkdp/hyperfine/releases/download/v1.6.0/hyperfine_1.6.0_amd64.deb"
    become: true
    tags: no-tests