- name: virtualbox
  hosts: 127.0.0.1
  connection: local
  tags: virtualbox
  tasks:

  - name: Add the Virtualbox APT new key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
    become: true

  - name: Add the Virtualbox APT old key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present
    become: true

  - name: Get upstream codename (bionic, xenial, trusty etc.)
    shell: >
      lsb_release -cus || lsb_release -cs
    changed_when: false
    register: upstream_codename

  - name: Add Virtualbox Repository
    apt_repository:
      repo: "deb https://download.virtualbox.org/virtualbox/debian {{ upstream_codename.stdout_lines[0] }} contrib"
      state: present
      filename: virtualbox.list
    become: true

  - name: Install Virtualbox
    apt:
      name: "{{ package }}"
      update_cache: yes
      cache_valid_time: 7200
      state: latest
    vars:
      package:
      - virtualbox-5.2
      - dkms
    become: true
