- name: Vivaldi
  hosts: 127.0.0.1
  connection: local
  tags: vivaldi
  tasks:

  - name: Add the Vivaldi APT key
    apt_key:
      url: https://repo.vivaldi.com/stable/linux_signing_key.pub
      id: 8D04CE49EFB20B23
      state: present
    become: true

  - name: Add Vivaldi Repository
    apt_repository:
      repo: "deb https://repo.vivaldi.com/stable/deb/ stable main"
      state: present
      filename: vivaldi.list
    become: true

  - name: Install Vivaldi
    apt:
      name: vivaldi-stable
      update_cache: yes
      cache_valid_time: 7200
      state: latest
    become: true

