- name: zsh
  hosts: 127.0.0.1
  connection: local
  tags: zsh
  tasks:

  - name: Install packages
    apt: name="{{ package }}" state=present
    vars:
      package:
      - zsh
      - wget
      - curl
      - git
      - rsync
      - fontconfig
    become: true
    register: zshInst

  - name: grep and register user_home
    shell: >
      egrep "^{{ ansible_user_id }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: user_home

  - name: ensure the ~/src-hub directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/src-hub"
      state: directory

  - name: clone oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: "{{ user_home.stdout_lines[0] }}/src-hub/oh-my-zsh"
      update: no

  - name: create symlink to oh-my-zsh
    file:
      path: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh"
      src: "{{ user_home.stdout_lines[0] }}/src-hub/oh-my-zsh"
      state: link

  - name: check if .zshrc exists
    stat:
      path: "{{ user_home.stdout_lines[0] }}/.zshrc"
    register: zshrc

  - name: back up existing .zshrc file if it exists
    when: zshrc.stat.exists and zshInst.changed
    copy:
      src: "{{ user_home.stdout_lines[0] }}/.zshrc"
      dest: "{{ user_home.stdout_lines[0] }}/.zshrc-orig"

  - name: Use your home in zshrc config
    replace:
      path: zsh_files/zshrc
      regexp: '\/home\/yourusername'
      replace: "/home/{{ ansible_user_id }}"
      backup: yes

  - name: Use your username in zshrc config
    replace:
      path: zsh_files/zshrc
      regexp: 'yourusername'
      replace: "{{ ansible_user_id }}"
      backup: yes

  - name: copy zshrc to user home
    copy:
      src: zsh_files/zshrc
      dest: "{{ user_home.stdout_lines[0] }}/.zshrc"
      force: yes

  - name: change user shell to zsh
    become: yes
    become_user: root
    command: chsh -s /bin/zsh "{{ ansible_user_id }}"
    when: zshInst.changed

  - name: ensure the fonts directory is present
    file:
      path: "{{ user_home.stdout_lines[0] }}/.local/share/fonts"
      mode: 0755
      state: directory
      recurse: true
    when: zshInst.changed

  - name: copy fonts
    synchronize:
      src: zsh_files/fonts
      dest: "{{ user_home.stdout_lines[0] }}/.local/share/"
    when: zshInst.changed

  - name: scan for new fonts
    command: fc-cache -fv {{ user_home.stdout_lines[0] }}/.local/share/fonts/
    when: zshInst.changed

  - name: clone powerlevel9k theme
    git:
      repo: https://github.com/bhilburn/powerlevel9k.git
      dest:  "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/themes/powerlevel9k"
      update: no

  - name: clone docker-machine completion
    git:
      repo: https://github.com/leonhartX/docker-machine-zsh-completion.git
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/docker-machine"
      update: no

  - name: clone fuzzy finder
    git:
      repo: https://github.com/junegunn/fzf.git
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/fzf"
      update: no
    register: fuzzyInst

  - name: install fuzzy finder
    command: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/fzf/install --bin"
    when: fuzzyInst.changed

  - name: clone fzf-zsh wrapper
    git:
      repo: https://github.com/Treri/fzf-zsh.git
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/fzf-zsh"
      update: no

  - name: clone sdkman zsh plugin
    git:
      repo: https://github.com/nobeans/zsh-sdkman.git
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/sdkman"
      update: no

  - name: clone zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

  - name: clone zsh-completions
    git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/zsh-completions"

  - name: create folder for flatpak plugin
    file:
      path: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/flatpak/"
      state: directory
      mode: 0755

  - name: copy flatpak plugin
    get_url:
      url: https://raw.githubusercontent.com/bilelmoussaoui/flatpak-zsh-completion/master/flatpak.plugin.zsh
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/flatpak/"

  - name: clone zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ user_home.stdout_lines[0] }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      update: no

  - name: Clone custom fonts
    git:
      repo: https://github.com/powerline/fonts.git 
      dest: "{{ user_home.stdout_lines[0] }}/src-hub/fonts"
      depth: 1
      update: no
    register: customFontsInst

  - name: Install custom fonts
    shell: "{{ user_home.stdout_lines[0] }}/src-hub/fonts/install.sh"
    when: customFontsInst.changed

  - name: Clone stderred, to colour sterred on red
    git:
      repo: https://github.com/sickill/stderred.git
      dest: "{{ user_home.stdout_lines[0] }}/src-hub/stderred"
      update: no

  - name: Install stderred dependencies
    apt: name="{{package}}" state=present
    vars:
      package:
        - build-essential
        - cmake
    become: true

  - name: Build stderred
    make:
      chdir: "{{ user_home.stdout_lines[0] }}/src-hub/stderred"
